config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update]
    resources :post_images, only: [:show, :index, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]
  end
  scope module: :user do
    get '/users/:id/favorites' => 'users#favorites'
    root to: 'homes#top'
    get '/users/my_page/' => 'users#show'
    get '/users/edit' => 'users#edit'
    patch '/users' => 'users#update'
    resources :users, only: [] do
      member do
        get :post_images
        get :favorites
      end
    end
    resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  end



  devise_for :user,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  has_many :image_tag_relations, dependent: :destroy
  has_many :tags, through: :image_tag_relations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :image

  validates :image, presence: true
  
  attr_accessor :tag

  def self.search(search)
    if search
      where(['title LIKE ?',"%#{search}%"])
    else
      all
    end
  end

  def favorited_by?(user)
    # binding.pry
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
    end
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images
  has_many :post_comments
  has_many :favorites

  has_one_attached :profile_image
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController

  def index
    @post_images = PostImage.page(params[:page]).search(params[:search]).order(id: "DESC")
    @post_images = @post_images.where("introduction LIKE ? ", '%' + params[:search] + '%') if params[:search].present?

    if params[:search].present? && Tag.find_by(name: params[:search]).present?
      post_image_ids = []
      Tag.find_by(name: params[:search]).post_image.each do |p|
        post_image_ids << p.id
      end
      post_image_ids = post_image_ids.uniq

      @post_images = PostImage.where(id: post_image_ids).page(params[:page]) if post_image_ids.present?
    end

    unless @post_images.present?
      @post_images = PostImage.all.page(params[:page]).order(id: "DESC")
    end

    if params[:tag_ids].present?
      post_image_ids = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          Tag.find_by(name: key).post_image.each do |p|
            post_image_ids << p.id
          end
        end
      end
      post_image_ids = post_image_ids.uniq
      @post_images = @post_images.where(id: post_image_ids) if post_image_ids.present?
    end

    # binding.pry
    # pp @post_images
  end
  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to admin_post_images_path
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

  private
    def user_params
      params.require(:user).permit(:is_active)
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end


end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController

  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end


  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/user/post_images_controller.rb
class User::PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    post_image = PostImage.new(post_image_params)
    post_image.user_id = current_user.id
    if post_image.save
      image_tag_relation = ImageTagRelation.new
      if post_image.tag.present?
        tag = Tag.find_by(name: post_image.tag)

        unless tag.present?
          tag = Tag.new
          tag.name = post_image.tag
          tag.save
        end

        image_tag_relation.tag_id = tag.id
        image_tag_relation.post_image_id = post_image.id
        image_tag_relation.save
      end
      redirect_to post_image_path(post_image.id)
    else
      flash[:alret] = "画像を選択してください"
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page]).search(params[:search]).order(id: "DESC")
    @post_images = @post_images.where("introduction LIKE ? ", '%' + params[:search] + '%') if params[:search].present?

    if params[:search].present? && Tag.find_by(name: params[:search]).present?
      post_image_ids = []
      Tag.find_by(name: params[:search]).post_image.each do |p|
        post_image_ids << p.id
      end
      post_image_ids = post_image_ids.uniq

      @post_images = PostImage.where(id: post_image_ids).page(params[:page]) if post_image_ids.present?
    end

    unless @post_images.present?
      @post_images = PostImage.all.page(params[:page]).order(id: "DESC")
    end

    if params[:tag_ids].present?
      post_image_ids = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          Tag.find_by(name: key).post_image.each do |p|
            post_image_ids << p.id
          end
        end
      end
      post_image_ids = post_image_ids.uniq
      @post_images = @post_images.where(id: post_image_ids) if post_image_ids.present?
    end

    # binding.pry
    # pp @post_images
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    post_image = PostImage.find(params[:id])
    #byebug
    post_image.update(post_image_params)
    if post_image.tag.present?
        tag = Tag.find_by(name: post_image.tag)

        unless tag.present?
          tag = Tag.new
          tag.name = post_image.tag
          tag.save
        end
        image_tag_relation = ImageTagRelation.new
        image_tag_relation.tag_id = tag.id
        image_tag_relation.post_image_id = post_image.id
        image_tag_relation.save
    end
    redirect_to post_image_path(post_image.id)
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end


  private
  def post_image_params
    params.require(:post_image).permit(:title, :introduction, :image, :tag, tag_ids: [])
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

   def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    if params[:format].present?
      @user = User.find(params[:format])
    else
      @user = current_user
    end
    #byebug
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    current_user.update(user_params)
    redirect_to users_my_page_path
  end

  def post_images
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).order(id: "DESC")
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_image_id)
    # binding.pry
    @favorite_posts = PostImage.find(favorites)
    @favorite_posts = Kaminari.paginate_array(@favorite_posts).page(params[:page])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/user/post_images/edit.html.erb
<div class="container">
  <h2>投稿編集</h2>
  <%= form_with model: @post_image, url: post_image_path, method: :patch do |f| %>
  <div class="row">
    <div class="post_image">
      <%= f.label :image do %>
        <%= image_tag @post_image.image, size: "500x400", class: 'avatar' %>
        <%= f.file_field :image, class: 'uploader', style: 'display:none', accept: "image/*" %>
      <% end %>
    </div>
    <div class="offset-md-1">
      <h4 class="border-bottom"><%= f.label "title" %></h4>
        <%= f.text_field :title %>
      <br>
      <br>
      <h4 class="border-bottom"><%= f.label "introduction" %></h4>
        <p><%= f.text_field :introduction %></p>
      <br>
      <h4 class="border-bottom"><%= f.label "Tag" %></h4>
        <p><%= f.text_field :tag %></p>
      <br>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
      <div>
        <%= f.submit '完了', class:"btn btn-success" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/user/post_images/index.html.erb
<div class="container">
  <h3>みんなの投稿</h3>
  <%= form_tag(post_images_path, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag "検索", :title => nil, class:"button is-info"%>

  <% end %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <% @post_images.each do |image| %>
      <%= link_to post_image_path(image.id ) do %>
        <%= image_tag image.image, class:"card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= link_to users_my_page_path(image.user.id) do %>
              <% if image.user.profile_image.attached? %>
                <%= image_tag image.user.profile_image, size: "75x75", class:"mt-3 rounded-circle"; %>
              <% else %>
                <%=  image_tag 'no_image', size: "75x75", class:"mt-3 rounded-circle"; %>
              <% end %>
            <% end %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_image_path(image.id), class:"text-dark") do %>
                <strong><i class="far fa-flag"></i><span> <%= image.title %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明：<%= image.introduction %></p>
            <span><i class="fas fa-user"></i> By <%= image.user.name %> ｜ </span>
            <span><%= link_to "#{image.post_comments.count} コメント", post_image_path(image.id), class:"text-dark" %></span>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @post_images %>
  </div>
</div>

app/views/user/post_images/new.html.erb
    <div class="text-danger">
      <%= flash[:alret] %>
    </div>
<div class="container">
  <h2>新規投稿</h2>
  <%= form_with model: @post_image, url: post_images_path, method: :post do |f| %>
  <div class="row">
    <div class="post_image">
      <%= f.label :image do %>
        <%= f.file_field :image, class: 'uploader', accept: "image/*" %>
      <% end %>
    </div>
    <div class="offset-md-1">
      <h4 class="border-bottom"><%= f.label "title" %></h4>
        <%= f.text_field :title %>
      <br>
      <br>
      <h4 class="border-bottom"><%= f.label "introduction" %></h4>
        <p><%= f.text_field :introduction %></p>
      <br>
      <div class='form-group'>
      <h4 class="border-bottom"><%= f.label "Tag" %></h4>
        <p><%= f.text_field :tag %></p>
      <br>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
              <div class='form-check'>
                  <%= tag.label class: 'form-check-label' do %>
                      <%= tag.check_box class: 'form-check-input' %>
                      <%= tag.text %>
                  <% end %>
              </div>
          <% end %>
      </div>
      <div>
        <%= f.submit '投稿', class:"btn btn-success" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/user/post_images/show.html.erb
<div class="container">
  <h2>投稿詳細</h2>
  <div class="row">
    <div class="post_image">
      <%= image_tag @post_image.image, size: "500x400" %>
    </div>
    <div class="offset-md-1">
      <h4 class="border-bottom">title</h4>
        <p><%= @post_image.title %></p>
      <br>
      <br>
      <h4 class="border-bottom">introduction</h4>
        <p><%= @post_image.introduction %></p>
      <br>
      <% @post_image.tags.each do |tag| %>
          <%= link_to tag.name, post_images_path(search: tag.name) %>
      <% end %>
      </br>
      <% if @post_image.user == current_user %>
        <%= link_to '編集する', edit_post_image_path, class:"btn btn-success" %></br>
        </br>
        <%= link_to '削除する', post_image_path(@post_image), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-danger" %>
      <% end %>
    </div>
  </div>
  <p>投稿日:<%= @post_image.created_at.strftime('%Y/%m/%d')%></p>
  <% if user_signed_in? %>
    <% if @post_image.favorited_by?(current_user) %>
      <p>
        <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
          ♥<%= @post_image.favorites.count %> いいね
        <% end %>
      </p>
      <% else %>
      <p>
        <%= link_to post_image_favorites_path(@post_image), method: :post do %>
          ♡<%= @post_image.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>



    <div>

      <p>コメント件数: <%= @post_image.post_comments.count %></p>

      <% @post_image.post_comments.each do |post_comment| %>
        <%= link_to users_my_page_path(post_comment.user) do %>
          <% if post_comment.user.profile_image.attached? %>
            <%= image_tag image.user.profile_image, size: "75x75", class:"mt-3 rounded-circle"; %>
          <% else %>
            <%=  image_tag 'no_image', size: "75x75", class:"mt-3 rounded-circle"; %>
          <% end %>
        <% end %>
        <%= post_comment.user.name%>
        <%= post_comment.created_at.strftime('%Y%m%d') %><%= post_comment.comment %>
        <% if post_comment.user == current_user %>
          <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
        <% end %>
      <% end %>

    </div>

    <div>
      <%=form_with model: [@post_image, @post_comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>
  <% end %>
</div>