config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update]
    resources :post_images, only: [:show, :index, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]
  end
  scope module: :user do
    get '/users/:id/favorites' => 'users#favorites'
    root to: 'homes#top'
    get '/users/my_page/' => 'users#show'
    get '/users/edit' => 'users#edit'
    patch '/users' => 'users#update'
    resources :users, only: [] do
      member do
        get :post_images
        get :favorites
      end
    end
    resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  end



  devise_for :user,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  has_many :image_tag_relations, dependent: :destroy
  has_many :tags, through: :image_tag_relations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :image

  validates :image, presence: true
  
  attr_accessor :tag

  def self.search(search)
    if search
      where(['title LIKE ?',"%#{search}%"])
    else
      all
    end
  end

  def favorited_by?(user)
    # binding.pry
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController

  def index
    @post_images = PostImage.page(params[:page]).search(params[:search]).order(id: "DESC")
    @post_images = @post_images.where("introduction LIKE ? ", '%' + params[:search] + '%') if params[:search].present?

    if params[:search].present? && Tag.find_by(name: params[:search]).present?
      post_image_ids = []
      Tag.find_by(name: params[:search]).post_image.each do |p|
        post_image_ids << p.id
      end
      post_image_ids = post_image_ids.uniq

      @post_images = PostImage.where(id: post_image_ids).page(params[:page]) if post_image_ids.present?
    end

    unless @post_images.present?
      @post_images = PostImage.all.page(params[:page]).order(id: "DESC")
    end

    if params[:tag_ids].present?
      post_image_ids = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          Tag.find_by(name: key).post_image.each do |p|
            post_image_ids << p.id
          end
        end
      end
      post_image_ids = post_image_ids.uniq
      @post_images = @post_images.where(id: post_image_ids) if post_image_ids.present?
    end

    # binding.pry
    # pp @post_images
  end
  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to admin_post_images_path
  end

end

app/controllers/user/post_images_controller.rb
class User::PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end

  def create
    post_image = PostImage.new(post_image_params)
    post_image.user_id = current_user.id
    if post_image.save
      image_tag_relation = ImageTagRelation.new
      if post_image.tag.present?
        tag = Tag.find_by(name: post_image.tag)

        unless tag.present?
          tag = Tag.new
          tag.name = post_image.tag
          tag.save
        end

        image_tag_relation.tag_id = tag.id
        image_tag_relation.post_image_id = post_image.id
        image_tag_relation.save
      end
      redirect_to post_image_path(post_image.id)
    else
      flash[:alret] = "画像を選択してください"
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page]).search(params[:search]).order(id: "DESC")
    @post_images = @post_images.where("introduction LIKE ? ", '%' + params[:search] + '%') if params[:search].present?

    if params[:search].present? && Tag.find_by(name: params[:search]).present?
      post_image_ids = []
      Tag.find_by(name: params[:search]).post_image.each do |p|
        post_image_ids << p.id
      end
      post_image_ids = post_image_ids.uniq

      @post_images = PostImage.where(id: post_image_ids).page(params[:page]) if post_image_ids.present?
    end

    unless @post_images.present?
      @post_images = PostImage.all.page(params[:page]).order(id: "DESC")
    end

    if params[:tag_ids].present?
      post_image_ids = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          Tag.find_by(name: key).post_image.each do |p|
            post_image_ids << p.id
          end
        end
      end
      post_image_ids = post_image_ids.uniq
      @post_images = @post_images.where(id: post_image_ids) if post_image_ids.present?
    end

    # binding.pry
    # pp @post_images
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    post_image = PostImage.find(params[:id])
    #byebug
    post_image.update(post_image_params)
    if post_image.tag.present?
        tag = Tag.find_by(name: post_image.tag)

        unless tag.present?
          tag = Tag.new
          tag.name = post_image.tag
          tag.save
        end
        image_tag_relation = ImageTagRelation.new
        image_tag_relation.tag_id = tag.id
        image_tag_relation.post_image_id = post_image.id
        image_tag_relation.save
    end
    redirect_to post_image_path(post_image.id)
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end


  private
  def post_image_params
    params.require(:post_image).permit(:title, :introduction, :image, :tag, tag_ids: [])
  end

end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/helpers/user/post_images_helper.rb
module User::PostImagesHelper
end

app/views/admin/post_images/index.html.erb
<div class="container">
  <h3>みんなの投稿</h3>
  <%= form_tag(admin_post_images_path, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag "検索", :title => nil, class:"button is-info"%>

  <% end %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <% @post_images.each do |image| %>
      <%= link_to admin_post_image_path(image.id ) do %>
        <%= image_tag image.image, class:"card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <% if image.user.profile_image.attached? %>
              <%= image_tag image.user.profile_image, size: "75x75", class:"mt-3 rounded-circle"; %>
            <% else %>
              <%=  image_tag 'no_image', size: "75x75", class:"mt-3 rounded-circle"; %>
            <% end %>          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_image_path(image.id), class:"text-dark") do %>
                <strong><i class="far fa-flag"></i><span> <%= image.title %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明：<%= image.introduction %></p>
            <span><i class="fas fa-user"></i> By <%= image.user.name %> ｜ </span>
            <span><%= link_to "#{image.post_comments.count} コメント", post_image_path(image.id), class:"text-dark" %></span>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @post_images %>
  </div>
</div>

app/views/admin/post_images/show.html.erb
<div class="container">
  <h2>投稿詳細</h2>
  <div class="row">
    <div class="post_image">
      <%= image_tag @post_image.image, size: "500x400" %>
    </div>
    <div class="offset-md-1">
      <h4 class="border-bottom">title</h4>
        <p><%= @post_image.title %></p>
      <br>
      <br>
      <h4 class="border-bottom">introduction</h4>
        <p><%= @post_image.introduction %></p>
      <br>
      <% @post_image.tags.each do |tag| %>
          <%= link_to tag.name, post_images_path(search: tag.name) %>
      <% end %>
      </br>

        <%= link_to '削除する', admin_post_image_path(@post_image), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-danger" %>
    </div>
  </div>
  <p>投稿日:<%= @post_image.created_at.strftime('%Y/%m/%d')%></p>

  <% if admin_signed_in? %>
      <p>コメント件数: <%= @post_image.post_comments.count %></p>
      <% @post_image.post_comments.each do |post_comment| %>
        <% if post_comment.user.profile_image.attached? %>
          <%= image_tag image.user.profile_image, size: "75x75", class:"mt-3 rounded-circle"; %>
        <% else %>
          <%=  image_tag 'no_image', size: "75x75", class:"mt-3 rounded-circle"; %>
        <% end %>
        <%= post_comment.user.name%>
        <%= post_comment.created_at.strftime('%Y%m%d') %><%= post_comment.comment %>
          <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-danger" %>
      <% end %>
    </div>
  <% end %>
</div>