config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update]
    resources :post_images, only: [:show, :index, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]
  end
  scope module: :user do
    get '/users/:id/favorites' => 'users#favorites'
    root to: 'homes#top'
    get '/users/my_page/' => 'users#show'
    get '/users/edit' => 'users#edit'
    patch '/users' => 'users#update'
    resources :users, only: [] do
      member do
        get :post_images
        get :favorites
      end
    end
    resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  end



  devise_for :user,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/image_tag_relation.rb
class ImageTagRelation < ApplicationRecord
  belongs_to :tag
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  has_many :image_tag_relations, dependent: :destroy
  has_many :tags, through: :image_tag_relations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :image

  validates :image, presence: true
  
  attr_accessor :tag

  def self.search(search)
    if search
      where(['title LIKE ?',"%#{search}%"])
    else
      all
    end
  end

  def favorited_by?(user)
    # binding.pry
    favorites.exists?(user_id: user.id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :image_tag_relations, dependent: :destroy
  has_many :post_image, through: :image_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
    end
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images
  has_many :post_comments
  has_many :favorites

  has_one_attached :profile_image
  def active_for_authentication?
    super && (is_active == true)
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to admin_tags_path
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update(tag_params)
    redirect_to admin_tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/post_images_helper.rb
module User::PostImagesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyBloom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/088fd842c6.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="border">
      <nav class="navbar navbar-expand navbar-light">
        <div class="container">
            <h3>
              <a href="/" class="text-dark">Happy<i class="fa-regular fa-flower-daffodil"></i>Bloom</a>
            </h3>
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "タグ編集", admin_tags_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_root_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "みんなの投稿",admin_post_images_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border' %>
              </li>
            <% elsif user_signed_in? %>
              <p>ようこそ、<%= current_user.name %>さん！</p>
              <li class="nav-item">
                <%= link_to "みんなの投稿",post_images_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "新しく投稿する",new_post_image_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "マイページ",users_my_page_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark border' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark border mr-md-3' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'nav-link text-dark border' %>
              </li>
            <% end %>
            </ul>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="border pt-5 pd-4">
      <div class="container"></div>
    </footer>
  </body>
</html>